#!/bin/bash


case $1 in
	--help )
		echo "Usage: now [PARAMETER]"
		echo "  --help          shows this dialog then exits."
		echo "  -f | --full     full string, e.g. 20230423091532"
		echo "  -d | --dash     dash seperator, e.g. 2023-04-23-09-15"
		echo "  -D | --detailed full, underscore seperator, e.g. 2023_04_23_09_15_32"
		echo "  -u | --unix     unix timestamp."
		echo "  -c | --clip     full, dash seperator then saves in clipboard."
		;;
	-f | --full )
		date +%Y%m%d%H%M%S
		;;
	-d | --dash )
		date +%Y-%m-%d-%H-%M
		;;
	-D | --detailed )
		date +%Y_%m_%d_%H_%M_%S
		;;
	-u | --unix )
		date +%s
		;; 
	-c | --clip )
	  date +%Y-%m-%d-%H-%M | xclip -sel clip
		;; 
	*)
		date +%Y-%m-%d-%H-%M
		exit 1;
		;;
esac


